name: logger_flutter
description: Flutter extension for logger. Please go there for documentation.
version: 1.0.1-nullsafety.0
homepage: https://github.com/HeyLor/logger_flutter
publish_to: none

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  logger: ^1.0.0-nullsafety.0
  sensors: ^2.0.0
