name: logger_flutter
description: Flutter extension for logger. Please go there for documentation.
version: 1.0.1
publish_to: https://rezipub.jfrog.io/artifactory/api/pub/pub-local-lantern
homepage: https://github.com/HeyLor/logger_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  logger: ^1.1.0
  sensors: ^2.0.0
